Quoting fix
structurizr/atlassian-confluence pull request #2
Opened 2019-11-08 09:00 UTC by matf

Fixes some quoting/escaping issues:

- HTML element IDs are now cleaned up to conform with the HTML 4 spec
  Acutally, in our internal fork of the plugin, we're simply using UUIDs for the 
  element IDs, but I didn't want to change the existing logic too much as I guess
  some users might rely on reproducible IDs being generated.
- The diagram key attribute value is escaped to avoid issues with invalid characters
  in diagram keys
- The generated HTML consistently uses double quotes. This avoids issues with single
  quotes in diagram keys

2019-11-19 19:29 UTC, simonbrowndotje commented
Thanks, looks good. Any chance you could rename the test classes though?

2019-11-19 19:32 UTC, simonbrowndotje requested changes
The test class names seem to have changed, which means we can't see the diffs.

2019-11-20 10:00 UTC, matf commented
Ok, removed the commit that renamed the test classes. The motivation was to make sure that the tests were run during the Maven build as their names don't matche pattern maven-surfefire expects. I change fix that in a separate PR.

2019-11-20 10:57 UTC, merged

2019-11-20 10:57 UTC, simonbrowndotje commented
Thanks!